
locale                   : "ko"
title                    : "제목"
title_separator          : "-"
name                     : "서윤하"
description              : "컴퓨터에 대한"
url                      : https://hahorse.github.io


baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : hahorse/hahorse.github.io
author:
 name             : "서윤하"
 avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
 bio              : "안녕하세요."
 location         : "Somewhere"
 theme: jekyll-theme-cayman
